import type { Metadata } from "next";
import localFont from "next/font/local";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next Admin Dashboard",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={"overflow-hidden"}>
        <NextTopLoader showSpinner={false} />
          <Toaster />
          {children}
      </body>
    </html>
  );
}

export default RootLayout;